/* Scanner.java */
/* Generated By:JavaCC: Do not edit this line. Scanner.java */
import java.io.*;

public class Scanner implements ScannerConstants {
  public static void main(String args []) throws ParseException, IOException
  {
      Scanner lexico = new Scanner(new FileInputStream(args[0]));
      lexico.Start();

  }

  final public void Start() throws ParseException {Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:
      case PUBLIC:
      case STATIC:
      case VOID:
      case MAIN:
      case STRING:
      case EXTENDS:
      case RETURN:
      case IF:
      case ELSE:
      case WHILE:
      case TRUE:
      case FALSE:
      case THIS:
      case NEW:
      case INT:
      case BOOLEAN:
      case LENGTH:
      case MAIS:
      case MENOS:
      case MULTIPLICAR:
      case MENOR:
      case OP_AND:
      case OP_NOT:
      case IGUAL:
      case PV:
      case AP:
      case FP:
      case AC:
      case FC:
      case ACO:
      case FCO:
      case PONTO:
      case VIRGULA:
      case SYSTEM_OUT_PRINTLN:
      case ID:
      case INTEGER_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:{
        jj_consume_token(CLASS);
System.out.println("Palavra reservada: class");
        break;
        }
      case PUBLIC:{
        jj_consume_token(PUBLIC);
System.out.println("Palavra reservada: public");
        break;
        }
      case STATIC:{
        jj_consume_token(STATIC);
System.out.println("Palavra reservada: static");
        break;
        }
      case VOID:{
        jj_consume_token(VOID);
System.out.println("Palavra reservada: void");
        break;
        }
      case MAIN:{
        jj_consume_token(MAIN);
System.out.println("Palavra reservada: main");
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
System.out.println("Palavra reservada: string");
        break;
        }
      case EXTENDS:{
        jj_consume_token(EXTENDS);
System.out.println("Palavra reservada: extends");
        break;
        }
      case RETURN:{
        jj_consume_token(RETURN);
System.out.println("Palavra reservada: return");
        break;
        }
      case IF:{
        jj_consume_token(IF);
System.out.println("Estrutura condicional : if");
        break;
        }
      case ELSE:{
        jj_consume_token(ELSE);
System.out.println("Estrutura condicional: else");
        break;
        }
      case WHILE:{
        jj_consume_token(WHILE);
System.out.println("Estrutura de repeti\u00c3\u00a7\u00c3\u00a3o: while");
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
System.out.println("Tipo booleano: True");
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
System.out.println("tipo booleano: False");
        break;
        }
      case THIS:{
        jj_consume_token(THIS);
System.out.println("Palavra reservada: this");
        break;
        }
      case NEW:{
        jj_consume_token(NEW);
System.out.println("Palavra reservada: new");
        break;
        }
      case INT:{
        jj_consume_token(INT);
System.out.println("Tipo: int");
        break;
        }
      case BOOLEAN:{
        jj_consume_token(BOOLEAN);
System.out.println("Tipo: Boolean");
        break;
        }
      case LENGTH:{
        jj_consume_token(LENGTH);
System.out.println("Palavra reservada: Length");
        break;
        }
      case MAIS:{
        jj_consume_token(MAIS);
System.out.println("Operador Mais");
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
System.out.println("Opera\u00c3\u00a7\u00c3\u00a3o Menos");
        break;
        }
      case MULTIPLICAR:{
        jj_consume_token(MULTIPLICAR);
System.out.println("Opera\u00c3\u00a7\u00c3\u00a3o Multiplicar");
        break;
        }
      case MENOR:{
        jj_consume_token(MENOR);
System.out.println("Operador Menor");
        break;
        }
      case OP_AND:{
        jj_consume_token(OP_AND);
System.out.println("Operador AND");
        break;
        }
      case OP_NOT:{
        jj_consume_token(OP_NOT);
System.out.println("Operador NOT");
        break;
        }
      case IGUAL:{
        jj_consume_token(IGUAL);
System.out.println("Igual");
        break;
        }
      case PV:{
        jj_consume_token(PV);
System.out.println("Ponto e virgula");
        break;
        }
      case AP:{
        jj_consume_token(AP);
System.out.println("Abre Parentese");
        break;
        }
      case FP:{
        jj_consume_token(FP);
System.out.println("Fecha Parentese");
        break;
        }
      case AC:{
        jj_consume_token(AC);
System.out.println("Abre Chaves");
        break;
        }
      case FC:{
        jj_consume_token(FC);
System.out.println("Fecha Chaves");
        break;
        }
      case ACO:{
        jj_consume_token(ACO);
System.out.println("Abre Colchetes");
        break;
        }
      case FCO:{
        jj_consume_token(FCO);
System.out.println("Fecha Colchetes");
        break;
        }
      case PONTO:{
        jj_consume_token(PONTO);
System.out.println("Ponto");
        break;
        }
      case VIRGULA:{
        jj_consume_token(VIRGULA);
System.out.println("Virgula");
        break;
        }
      case SYSTEM_OUT_PRINTLN:{
        jj_consume_token(SYSTEM_OUT_PRINTLN);
System.out.println("System.out.println");
        break;
        }
      case ID:{
        t = jj_consume_token(ID);
System.out.println("Identificador: " + t.image);
        break;
        }
      case INTEGER_LITERAL:{
        t = jj_consume_token(INTEGER_LITERAL);
System.out.println("Integer: " + t.image);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
}

  /** Generated Token Manager. */
  public ScannerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xffffff80,0xffffff80,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1bff,0x1bff,};
	}

  /** Constructor with InputStream. */
  public Scanner(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Scanner(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ScannerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Scanner(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ScannerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ScannerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Scanner(ScannerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ScannerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[45];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 2; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 45; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
